stopCmdList = [
    'jobsched',
    'sensord',
    'playman',
    'execd',
#    'vspoold',
    'renderd',
    'receiverdPri',
    'receiverd',
    'datad',
    'eventd',
    'nsd',
]

startCmdList = [
    micoBinary('nsd', nsdArgs),
    sleep("0.5"),
    micoBinary('eventd', orbNameArgs),
    sleep("0.5"),
    pythonUtil('makechan', eventChannelNameArg),
    istarBinary('datad', HIGH_PRI),
    pythonUtil('setVersions'),
    pythonUtil('loadStaticValues'),
    istarBinary('receiverd', HIGH_PRI),
    istarBinary('receiverd', HIGH_PRI, 'receiverdPri'),
    istarBinary('renderd', HIGH_PRI),
 #   istarBinary('vspoold', HIGH_PRI),
    rsload(TWCPERSDIR + '/util/Video.rs'),
    pythonDaemon('execd'),
    pythonDaemon('execd', DFLT_PRI, 'playman'),
#    pythonDaemon('sensord', HIGH_PRI),
    sendSignal('execd', 'altFeed.resetChannel', ''),
    loadPlugin('execd', 'map'),
    loadPlugin('playman', 'init'),
    loadPlugin('playman', 'playCmd.bulletin'),
    pythonDaemon('jobsched', LOW_PRI),
]

startDataCmdList = [
    micoBinary('nsd', nsdArgs),
    sleep("0.5"),
    micoBinary('eventd', orbNameArgs),
    sleep("0.5"),
    pythonUtil('makechan', eventChannelNameArg),
    istarBinary('datad', HIGH_PRI),
    pythonUtil('setVersions'),
    pythonUtil('loadStaticValues'),
    istarBinary('receiverd', HIGH_PRI),
    istarBinary('receiverd', HIGH_PRI, 'receiverdPri'),
    pythonDaemon('execd'),
    sendSignal('execd', 'altFeed.resetChannel', ''),
    loadPlugin('execd', 'map'),
    pythonDaemon('jobsched', LOW_PRI),
]

